<?php
echo "<form action = \"insert_data.php\" method = \"POST\">";
echo "<table>";
echo "<tbody>";
echo "<tr>";
echo "<td><p>Username</p></td>";
echo "<td><input type = \"text\" name = \"user_name\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td><p>Email</p></td>";
echo "<td><input type = \"email\" name = \"user_email\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td><p>Gender</p></td>";
echo "<td><select name = \"user_gender\">";
echo "<option value = \"male\"><p>male</p></option>";
echo "<option value = \"female\"><p>female</p></option>";
echo "<option value = \"other\"><p>other</p></option>";
echo "</select></td>";
echo "</tr>";
echo "<tr>";
echo "<td><p>Password</p></td>";
echo "<td><input type = \"password\" name = \"user_pass\"></td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type = \"submit\" ></td>";
echo "</tr>";
echo "</tbody>";
echo "</table>";
echo "</form>";
?>